Fix-NPM scripts changed from nest to stencil [05-temporal-package]
SamagraX-Stencil/stencil pull request #117
Opened 2024-06-04 16:35 UTC by ShivamAher30

# Pull Request: Update Default NPM Scripts

## Description

This pull request aims to address an issue where NPM scripts lead to an error when executed using the `nest` command as the default. The proposed changes update the default command in the `package.json` file from `nest` to `stencil`.

## Files Changed

- `stencil/sample/05-temporal-package/package.json`

## Proposed Changes

The default NPM scripts in the `package.json` file have been updated from `nest` to `stencil`. This change ensures that the scripts execute correctly and aligns with the project's dependencies and tooling.

}

2024-06-04 16:42 UTC, techsavvyash requested changes
update the README.md of the project to add a step for installation of stencil-cli as well.

2024-06-04 17:19 UTC, ShivamAher30 commented
Will do it sir

2024-06-05 06:59 UTC, ShivamAher30 commented
Added the cmd for stencil-cli setup

2024-06-06 15:36 UTC, techsavvyash approved these changes

2024-06-06 15:37 UTC, merged