Fixed-illegal-urlpassin-as-param
SamagraX-Stencil/stencil pull request #125
Opened 2024-06-09 09:10 UTC by ShivamAher30

### Issue #120: Path Traversal Vulnerability via Illegal URL Destination Parameter

**Problem:**
Normally, when passing the destination parameter, a file is downloaded. However, if characters like `../` are added and passed as a parameter after URL encoding, it enables access to files outside of the directory. For instance, the string `../test/jest-e2e.json`, when URL encoded, can be passed as the destination parameter: `localhost:3000/files/download/..%2Ftest%2Fjest-e2e.json`. This results in the file being served as a response, potentially exposing sensitive information.

**How to Recreate:**
1. Pass a URL-encoded string containing `../` as the destination parameter.
2. Access the corresponding endpoint, for example: `localhost:3000/files/download/..%2Ftest%2Fjest-e2e.json`.
3. The content of the `jest-e2e.json` file is served as a response, revealing potentially sensitive data.

**Solution:**
To mitigate this vulnerability, we need to validate the destination parameter to ensure it does not contain any illegal characters or patterns that could lead to path traversal attacks. We can achieve this by implementing server-side validation and rejecting requests with invalid destination parameters.

**Changes:**
1. Implement validation checks for the destination parameter in the affected endpoint handler controller.
2. If the destination parameter contains illegal characters or patterns indicative of path traversal attempts, return an appropriate error response and do not serve the requested file.

### Test Cases

**Allowed Test Cases:**
The following folder structure and test cases are considered safe:
1. `new.txt`
   ![new.txt](https://github.com/SamagraX-Stencil/stencil/assets/147340395/f4748090-1211-4782-b2bd-fc801ae2ef99)
2. `demo.c`
   ![demo.c](https://github.com/SamagraX-Stencil/stencil/assets/147340395/9e9de9d3-c8f0-4124-a410-2314ad35fdc0)
3. `new1232.js`
   ![new1232.js](https://github.com/SamagraX-Stencil/stencil/assets/147340395/910f19fd-3546-4e41-968a-384e1cdbed48)

**Rejected Test Cases:**
Requests attempting to access `../.env` after URL encoding, which may leak information stored in the `.env` file, are rejected:
![Rejected Request](https://github.com/SamagraX-Stencil/stencil/assets/147340395/0eaaeac9-4b29-4daa-ae60-1a3d58a876db)

2024-06-25 18:44 UTC, DarrenDsouza7273 requested changes
- Update the Logging method using Nestjs Logger.
- Add a check for `if fileStream is null` .
- (Line:66) @techsavvyash  Do u feel using `res.send(fileStream)` will be better than `fileStream.pipe(res.raw)`.

2024-06-25 18:50 UTC, DarrenDsouza7273 commented on packages/common/test/file-upload/file-upload.controller.spec.ts
> +    RejectedDestination.map(async (file) => {
RejectedDestination.map(async (file)
```suggestion
    RejectedDestination.forEach(async (file) => {
```

2024-06-25 18:52 UTC, DarrenDsouza7273 commented on packages/common/test/file-upload/file-upload.controller.spec.ts
> +    RejectedDestination.map(async (file) => {
```suggestion
    RejectedDestination.forEach(async (file) => {
```

2024-07-09 18:09 UTC, techsavvyash commented
closing this out since #159 has a fix handling for it.

2024-07-09 18:09 UTC, closed without merging