add empty file check and tests for the same
SamagraX-Stencil/stencil pull request #175
Opened 2024-07-12 06:14 UTC by gnaaruag

## Checklist
Make sure you have
- [ ] Added relevant `@nestjs/swagger` decorators wherever required 
- [x] Added test cases (unit and integration) wherever required

## Description
- this adds a empty file upload check to the `file-upload.controller.ts` in `packages/common/src` 
- also adds tests for correct file upload, empty file upload
- if the file is found to be empty a status code of 400 is sent, else it is uploaded further according to `process.env.STORAGE_MODE`
- in `file-upload.interceptor` the line `request.raw = request.raw || request;` allows for valid request body to pass through

## Steps to test
**to test manually** 
create a post request to `/file/upload-file`  
test with empty file and non empty file via `multipart/form-data`

**to run automated test**
navigate to `samples/04-file-upload` and run `npm run test:e2e`

fixes #156

2024-07-24 11:26 UTC, techsavvyash requested changes

2024-07-24 11:26 UTC, techsavvyash commented on packages/common/test/app.e2e-spec.ts
> +    fs.writeFileSync(testFilePath, 'abcd');
is this line required in the test case? doesn't seem to be getting used. If it is required, make sure to unlink the file as a test cleanup

2024-07-24 11:26 UTC, techsavvyash commented on packages/common/test/app.e2e-spec.ts
> +    console.log('Response:', response.body);
remove the log statement.

2024-07-24 11:26 UTC, techsavvyash commented on sample/04-file-upload/test/app.e2e-spec.ts
> +    console.log('Response:', response.body);
remove the log

2024-07-24 11:26 UTC, techsavvyash commented on sample/04-file-upload/test/app.e2e-spec.ts
we can remove these tests altogether I see no point in duplicating them across the app, if the `packages/common` passes then it's good enough

2024-07-24 16:50 UTC, gnaaruag commented on sample/04-file-upload/test/app.e2e-spec.ts
we currently dont have any provision to run e2e tests in `packages/common` 
so we should let the tests run in `04-file-upload` and remove it from `packages/common`

2024-07-28 05:17 UTC, gnaaruag commented on sample/04-file-upload/test/app.e2e-spec.ts
resolved

2024-08-09 19:31 UTC, merged