Tests for file upload interceptor
SamagraX-Stencil/stencil pull request #176
Opened 2024-07-15 01:51 UTC by gnaaruag

## Checklist
Make sure you have
- [ ] Added relevant `@nestjs/swagger` decorators wherever required 
- [x] Added test cases (unit and integration) wherever required

## Description
This PR adds tests described in #50 to `file-upload.interceptor.spec.ts`

## Steps to test
Navigate to `packages/common/test` and run `npm run test interceptor/file-upload.interceptor.spec.ts`

2024-07-15 01:56 UTC, gnaaruag commented
only three of the mentioned tests were added, rest will be added in a bit. have drafted this so as to help co-contributors keep track of what's done and whats not

2024-07-24 12:41 UTC, techsavvyash requested changes

2024-07-24 12:41 UTC, techsavvyash commented on sample/04-file-upload/test/app.e2e-spec.ts
duplication of tests is not required, the tests in `packages/common` seem fine

2024-07-24 16:54 UTC, gnaaruag commented on sample/04-file-upload/test/app.e2e-spec.ts
since we cannot run e2e tests in `packages/common` i have left a copy in `packages/common`, in order for it to run it needs to be in `04-file-upload`.

do let me know ill take them off from whereever we decide to

2024-07-28 05:14 UTC, gnaaruag commented on sample/04-file-upload/test/app.e2e-spec.ts
has been resolved

2024-08-09 19:31 UTC, merged

2024-09-17 08:23 UTC, VedantKhairnar commented
Hey there,
Thanks for your contribution.
As part of Augtoberfest, we want to reward you for your contributions, so pls fill out [this form](https://forms.gle/VBDUPWMYcZEbmVrQ9) by 19th Sept.
Thanks.