Feat:Initial implementation of file-upload-tests
SamagraX-Stencil/stencil pull request #89
Opened 2024-03-26 19:09 UTC by vsvishalsharma

fixes #50 

Tests included:

1. **Test for Instantiation**: 
2. **Test for Handling File Upload**:
3. **Test for Handling Uploaded File**:
4. **Test for Error Handling**:

2024-04-01 12:11 UTC, vsvishalsharma commented
@sooraj1002 can you suggest any changes that i need to make

2024-04-03 15:47 UTC, vsvishalsharma commented
@techsavvyash 
shall i write more test cases like handling large file size ,empty file,invalid file format

2024-04-07 05:23 UTC, Savio629 commented
@vsvishalsharma 
Can you exclude the unnecessary file from the commit( package-lock and yarn lock)?

2024-04-07 06:08 UTC, vsvishalsharma commented
@Savio629 done

2024-04-07 06:23 UTC, sooraj1002 commented on packages/common/test/file-upload.interceptor.spec.ts
> +  });
can we make this a little more descriptive

2024-04-07 07:37 UTC, sooraj1002 commented
@vsvishalsharma could you send a video showing the working tests?

2024-04-07 07:40 UTC, sooraj1002 requested changes

2024-04-15 09:33 UTC, vsvishalsharma commented
![image](https://github.com/SamagraX-Stencil/stencil/assets/131687529/55acf5ce-7491-4db3-8019-61c432d21364)
@sooraj1002 
sorry for the late response i just wanted to double check everything and i have made some changes in the FastifyFileInterceptor to support the test cases better

2024-04-15 09:37 UTC, vsvishalsharma commented
@sooraj1002  kindly ignore jest.unit.json fiel as it is there only for testing purpose

2024-04-15 10:04 UTC, techsavvyash commented on packages/common/src/interceptors/file-upload.interceptor.ts
Could you please explain what these changes are doing and why were they required? If you found a bug please feel free to report it by opening a issue ticket.

2024-04-15 10:04 UTC, techsavvyash commented
> @sooraj1002  kindly ignore jest.unit.json fiel as it is there only for testing purpose 

Please remove any and all files that are to be ignored.

2024-04-15 10:06 UTC, techsavvyash commented
> ![image](https://github.com/SamagraX-Stencil/stencil/assets/131687529/55acf5ce-7491-4db3-8019-61c432d21364)
> 
> @sooraj1002 
> 
> sorry for the late response i just wanted to double check everything and i have made some changes in the FastifyFileInterceptor to support the test cases better 

Please make sure to manage and report any bugs that you found by opening an issue ticket and then submit code changes relating to that.

2024-04-15 10:21 UTC, vsvishalsharma commented
> > ![image](https://private-user-images.githubusercontent.com/131687529/322427546-55acf5ce-7491-4db3-8019-61c432d21364.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTMxNzY0MDksIm5iZiI6MTcxMzE3NjEwOSwicGF0aCI6Ii8xMzE2ODc1MjkvMzIyNDI3NTQ2LTU1YWNmNWNlLTc0OTEtNGRiMy04MDE5LTYxYzQzMmQyMTM2NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxNVQxMDE1MDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MWFkMmFmMzcwNTA5YzVjOGFjMzE0ZTIzNzc0YmZlZWZjNTcxMWI2NjhkMDgyOGNkM2M1MjAzMzVlMGM5ZTJhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.StH9vzxfz_ag7R6HxsbV6K7qXX4gwYW5fgnYIwUa9f4)
> > @sooraj1002
> > sorry for the late response i just wanted to double check everything and i have made some changes in the FastifyFileInterceptor to support the test cases better
> 
> Please make sure to manage and report any bugs that you found by opening an issue ticket and then submit code changes relating to that.

![image](https://github.com/SamagraX-Stencil/stencil/assets/131687529/47937495-1809-47fc-a5c4-08dff4f76684)

the issue is that appmodule.ts is not present in the the directory specified` "../../../packages/user-service/src/app.module"` this is the correct location for it

2024-04-16 09:44 UTC, techsavvyash commented on packages/common/src/interceptors/file-upload.interceptor.ts
can you provide a TL;DR :)

2024-04-16 11:10 UTC, vsvishalsharma commented on packages/common/src/interceptors/file-upload.interceptor.ts
Sorry my bad the changes are in respect for the test cases .The changes **enhance error handling**, add **file format validation**, and improve test case structure. They make the interceptor more robust, secure, and maintainable.

2024-04-16 11:16 UTC, vsvishalsharma commented on packages/common/src/interceptors/file-upload.interceptor.ts
If the test cases of file format and validation and should handle error are not required then the interceptor can be reverted back to the original state but the changes only provide a enhancement over the previous version of the ineterceptor 
```
it('should handle an invalid file format', async () => {
    const file = { originalname: 'test.txt', mimetype: 'text/plain' };
    const context = createMockContext(file);
    const nextHandler = createMockNextHandler();

    await expect(interceptor.intercept(context, nextHandler)).rejects.toThrow('Invalid file format');
  });
```

2024-04-17 09:16 UTC, vsvishalsharma commented
![image](https://github.com/SamagraX-Stencil/stencil/assets/131687529/0a0dc5fb-f829-41c3-b7df-56942ae19906)
the test are working fine waiting for your response on the interceptor part shall i change it or not

2024-05-01 17:49 UTC, vsvishalsharma commented
hey @techsavvyash @sooraj1002  looking forward for your review

2024-05-02 07:48 UTC, techsavvyash requested changes

2024-05-02 07:48 UTC, techsavvyash commented on packages/user-service/yarn.lock
revert this change

2024-05-02 07:48 UTC, techsavvyash commented on packages/common/src/interceptors/file-upload.interceptor.ts
revert these changes and open a issue ticket if you have found a bug in the component, so that we can properly test and architect the fix for it.

2024-05-02 07:48 UTC, techsavvyash commented on packages/common/test/file-upload.interceptor.spec.ts
> +  });
don't nitpick

2024-05-02 07:48 UTC, techsavvyash commented on packages/common/test/file-upload.interceptor.spec.ts
> +  it('should handle getting an uploaded file when file is null', async () => {
why are we allowing uploaded files to be null? isn't this the same as getting files when they are not present?

2024-05-02 07:48 UTC, techsavvyash commented on packages/common/test/file-upload.interceptor.spec.ts
> +  it('should handle an invalid file format', async () => {
why are we not allowing `text/plain` as a file format? the interceptor as of now has no restrictions on the formats of the files which can be uploaded.

2024-05-02 07:49 UTC, techsavvyash commented
> hey @techsavvyash @sooraj1002 looking forward for your review

have added a few comments please resolve them and we can close this PR out.

2024-05-02 14:20 UTC, vsvishalsharma commented
@techsavvyash sir revereted back the interceptor

2024-05-03 13:46 UTC, merged