feat: CRUD API's
SamagraX-Stencil/stencil pull request #90
Opened 2024-04-08 07:14 UTC by Apurv428

Created generic crud APIs

Issue: https://github.com/SamagraX-Stencil/stencil/issues/2

2024-04-16 17:26 UTC, techsavvyash requested changes
I think we already have the logic to generate generic services and modules and even controllers in the schematics already. 
The extractor is a promising thing to add but I think the crude logic will not be very maintainable, let's use this [prisma-parser](https://github.com/techsavvyash/pp) to parse the `schema.prism` files in a JSON model and then use it to add types.
Also, I believe the code for this is best added in the [schematics](https://github.com/samagrax-stencil/schematics) since all the code generation and injection logic is consolidated there for the `stencil-cli` to use.

2024-04-16 17:26 UTC, techsavvyash commented on sample/01-all-features/src/generic/generic.controller.ts
> +import { Request, Response } from "express";
stencil is fastify based.

2024-04-16 17:26 UTC, techsavvyash commented on sample/01-all-features/src/generic/generic.model.ts
i think this file was committed by mistake

2024-05-10 16:35 UTC, Savio629 commented
// @Apurv428

2024-08-09 19:33 UTC, techsavvyash commented
Closing this since there is no movement.

2024-08-09 19:33 UTC, closed without merging